<?php

namespace App\Models\Settings;

use Illuminate\Database\Eloquent\Model;

class PageHeading extends Model
{
    //
    protected $fillable = [
        'title',
        'description',
        'web_banner',
        'mob_banner',
        'btn_1',
        'btn_1_url',
        'G_rating_image',
        'why_title',
        'who_image',
        'who_title',
        'who_subtitle',
        'who_description',
        'btn_2',
        'btn_2_url',
        'service_title',
        'service_subtitle',
        'service_description',
        'covered_image',
        'covered_title',
        'covered_description',
        'btn_3',
        'btn_3_url',
        'review_title',
        'review_subtitle',
        'review_description',
        'btn_4',
        'btn_4_url',
        'help_title',
        'btn_5',
        'btn_5_url',
        'about_bg_image',
        'about_title',
        'about_subtitle',
        'ourstory_image',
        'ourstory_title',
        'ourstory_subtitle',
        'ourstory_description',
        'btn_6',
        'btn_6_url',
        'whychoose_title',
        'whychoose_subtitle',
        'whychoose_description',
        'whychoose_image',
        'btn_7',
        'btn_7_url',
        'gallery_bg_image',
        'gallery_title',
        'gallery_subtitle',
        'news_title',
        'news_subtitle',
        'news_description',
        'what_we_do_title',
        'what_we_do_subtitle',
        'what_we_do_description',
        'contact_bg_image',
        'contact_title',
        'contact_subtitle',
        'contact_heading',
        'contact_subheading',
        'contact_number',
        'contact_email',
        'whatsapp_number',
        'contact_address',
        'contact_maps',
        'facebook_link',
        'twitter_link',
        'instagram_link',
      
    ];
    protected $casts = [
      'web_banner' => 'array',
      'mob_banner' => 'array',
    ];
}
